
-- ===================================================
-- HEALTHCARE MANAGEMENT DATA ANALYSIS USING SQL
-- ===================================================

-- Database Exploration
-- 1. Patient Analysis
-- 2. Doctor Analysis
-- 3. Hospital Analysis
-- 4. Medical Condition Analysis
-- 5. Billing Analysis
-- 6. Insurance Analysis
-- 7. Blood Group Analysis
-- 8. Date Analysis
-- 9. Advanced SQL Analysis

-- Creating Database named Healthcare.
Create database healthcare;

-- Selecting Healthcare database to query.
use healthcare;

-- Viewing Data on Database
select * from healthcare_data;

-- Describing characteristics of table.
exec sp_help 'healthcare_data';


-- 1. Patient Analysis
-- 1.1 counting total number of records in the healthcare_data table.
select count(*) as Total_records from healthcare_data;

-- 1.2 counting total number of male and female patients
select Gender,count(Gender) from healthcare_data group by Gender;

--1.3 Average patient age
select avg(Age) as Avg_patient_age from healthcare_data; 

--1.4 Youngest and oldest patient age
select min(Age) as Yougest_patient_age,max(Age) as Oldest_patient_age from healthcare_data;

--1.5 Number of patients in Each blood Group
select Blood_Type,count(Blood_Type) as Total_patients from healthcare_data group by Blood_Type;

--1.6 Patient grouped by age category
select Age_category,count(Age_category) as Number_of_patients from
(select case when Age<=18 then 'children(0-18)'
			when Age>18 and Age<=40 then 'Adults(18-40)'
			when Age>40 and  Age<=60 then 'Middle Aged(40-60)'
			else 'Senior Citizen(60+)'
			end Age_category
from healthcare_data)t group by Age_category order by count(Age_category);

--1.7 Average of age Male and female
select Gender,avg(Age) as Average_age from healthcare_data group by Gender;



--2. Doctor Analysis
--2.1 Number of doctors
select count(distinct Doctor) as Number_of_doctors from healthcare_data ;

--2.2 Number of Patients treated by each doctor
SELECT Doctor, COUNT(*) AS Patients_Treated
FROM healthcare_data
GROUP BY Doctor
ORDER BY Patients_Treated DESC;

--2.3 Doctors treating highest number of patients.
select top 10 Doctor,count(*) as Patients_Treated FROM healthcare_data
GROUP BY Doctor ORDER BY Patients_Treated DESC ;

--2.4 Average billing generated by each doctor
select Doctor,Round(avg(Billing_Amount),2) as Avg_Billing_amount from healthcare_data group by Doctor;



-- 3. Hospital Analysis
--3.1 Total hospitals in dataset.
select count(distinct Hospital) as Total_Hospitals from healthcare_data;

--3.2 Top 10 hospitals that treated highest Number of patients .
select top 10 Hospital,count(name) as No_of_Patients from healthcare_data group by Hospital order by No_of_Patients desc;

--3.3 Top 10 Hospital generating highest revenue.
select top 10 Hospital,round(sum(Billing_Amount),2) as Total_amount from healthcare_data group by Hospital order by Total_amount desc;

--3.4 Hospitals that have negative revenue.
select Hospital,round(sum(Billing_Amount),2) as Total_amount from healthcare_data
group by Hospital having  round(sum(Billing_Amount),2)<0 order by Total_amount;



-- 4. Medical Condition Analysis
--4.1 Number of patients for each disease..
select Medical_Condition,count(Name) as No_of_Patients from healthcare_data 
group by Medical_Condition order by No_of_Patients desc;

--4.2 Average billing amount by medical condition.
select Medical_Condition,round(avg(Billing_Amount),2) as Avg_Billing_amount from healthcare_data 
group by Medical_Condition order by Avg_Billing_amount desc;

--4.3 Average patient age by disease.
select Medical_Condition,avg(Age) as Avg_patient_age from healthcare_data 
group by Medical_Condition;

--4.5 Disease distribution by gender
SELECT
    Medical_Condition,
    SUM(CASE WHEN Gender = 'Male' THEN 1 ELSE 0 END) AS Male_Patients,
    SUM(CASE WHEN Gender = 'Female' THEN 1 ELSE 0 END) AS Female_Patients,
    COUNT(*) AS Total_Patients
FROM healthcare_data
GROUP BY Medical_Condition
ORDER BY Total_Patients DESC;

-- 5. Billing Analysis
--5.1 Total revenue.
select sum(Billing_Amount) as Total_revenue from healthcare_data;

--5.2 Average billing amount,Highest bill and Lowest bill
select avg(Billing_Amount) as Avg_Billing_amt,
	   Max(Billing_Amount) as Highest_bill,
	   min(Billing_Amount) as Lowest_bill
from healthcare_data;

--5.3 Top 10 highest billing patients
select distinct top 10 Name,Billing_Amount from healthcare_data order by Billing_Amount desc;


-- 6. Insurance Analysis
--6.1 Number of patients by insurance provider
select Insurance_Provider,Count(name) as No_of_patients from healthcare_data group by Insurance_Provider;

--6.2 Most used insurance provider.
select top 1 Insurance_Provider,Count(name) as No_of_patients from healthcare_data 
group by Insurance_Provider order by  No_of_patients desc;


-- 7. Blood Group Analysis
--7.1 Blood group distribution
select Blood_Type,count(*) as Total_Patients from healthcare_data group by Blood_Type order by Total_Patients desc;

--7.2 Most common blood group.
select top 1 Blood_Type,count(*) as Total_Patients from healthcare_data group by Blood_Type order by Total_Patients desc;



-- 8. Date Analysis
--8.1 Admissions per year.
select year(Date_of_Admission) as 'year' ,count(*) as No_of_patients from healthcare_data 
group by year(Date_of_Admission) order by year;

--8.2 Admissions per month
select format(Date_of_Admission, 'MMM') AS Month, count(*) AS No_of_Patients
from healthcare_data
group by Month(Date_of_Admission), format(Date_of_Admission, 'MMM')
order by month(Date_of_Admission);

--8.3 Yearly revenue.
select year(Date_of_Admission) as 'Year', round(sum(Billing_Amount),2) as Total_revenue from healthcare_data 
group by year(Date_of_Admission) order by Year;



-- 9. Advanced SQL Analysis
--9.1 Running total of yearly revenue..
select
    year,
    revenue,
    sum(revenue) over(order by year) as running_revenue
from (
    select
        year(date_of_admission) as year,
        sum(billing_amount) as revenue
    from healthcare_data
    group by year(date_of_admission)
) as yearly_revenue
order by year;

--9.2 categorizes patients as high, medium, or low risk based on their medical condition
Select Name, Medical_Condition, Test_Results,
Case 
		when Test_Results = 'Inconclusive' then 'Need More Checks / CANNOT be Discharged'
        when Test_Results = 'Normal' then'Can take discharge, But need to follow Prescribed medications timely' 
        when Test_Results =  'Abnormal' then 'Needs more attention and more tests'
        end as  'Status', Hospital, Doctor
from healthcare_data;
